certificates/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('addcertificats/', views.addcertificates, name='addcertificates'),
    path('set_certificates/', views.set_certificates, name='certificates'),
    path('search_certificates/', views.search_certificates, name='search_certificates'),
    
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.w3school, name='w3school'),
    path('admin_log', views.admin_log, name='admin_log'),
    path('logout/', views.logout_view, name = 'logout'),
]

djangogit/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('w3school/', include('core.urls')),
    path('students/', include('students.urls')),
    path('certificates/', include('certificates.urls'))
]

certificates/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import SendTransaction
import json
from datetime import date
import hashlib

# Create your models here.yy
class Certificates(models.Model):
    code = models.CharField(max_length=5, unique=True) #unique code
    name_certificate = models.CharField(max_length=50, unique=True)
    note = models.CharField(max_length=200)
    def __str__(self):
        return self.name_certificate + ',' + self.code

    
class SetCertificates(models.Model):
    students = models.ForeignKey(User, on_delete=models.CASCADE)
    certificates = models.ForeignKey(Certificates, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)
    vote = models.PositiveIntegerField()
    hash = models.CharField(max_length=255, blank=True, null=True)
    txid = models.CharField(max_length=255, blank=True, null=True) 
    
    def write(self):
        data = {
            'code' : self.certificates.code,
            'first_name' : self.students.first_name,
            'last_name' : self.students.last_name,
            'certificate' : self.certificates.name_certificate,
            'note' : self.certificates.note,
            'vote' : self.vote,
            'date' : str(self.date)
        }

        data_json = json.dumps(data)
        
        print(data, 'json:', data_json)
        return SendTransaction(data_json)

    def save(self):
        self.txid = self.write()
        super (SetCertificates, self).save()

    def __str__(self) :
        return self.certificates.name_certificate

certificates/forms.py
from django import forms
from .models import Certificates

class NewCertificates(forms.ModelForm):
    class Meta:
        model = Certificates
        fields = ['code', 'name_certificate', 'note']
    
    def clean_code(self):
        code = self.cleaned_data['code']
        return code
    
    def clean_name_certificate(self):
        name_certificate = self.cleaned_data ['name_certificate']
        if name_certificate:
            name_certificate = name_certificate.strip()
        return name_certificate

    widget = {
        'code' : forms.TextInput(attrs={'class' : 'form-control'}),
        'name_certificate' : forms.TextInput(attrs={'class' : 'form-control'}),
        'note' : forms.TextInput(attrs={'class' : 'form-control'}),
    }

certificates/views.py
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from .forms import NewCertificates
from django.contrib.auth.models import User
from .models import Certificates,SetCertificates
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='admin_log')
@staff_member_required
def addcertificates(request):
    certificates = Certificates.objects.all()
    if request.method == 'POST':
        form = NewCertificates(request.POST) 
        if form.is_valid():
            form.save()
            messages.success(request, 'Certificate added successfully')
            return redirect('addcertificates')
        messages.error(request, 'Error! Please check your data.')
    else:
        form = NewCertificates()
    c_messages = messages.get_messages(request)
    return render(request, 'certificates/addcertificates.html', {'form': form, 'c_messages' : c_messages, 'certificates': certificates})

@login_required(login_url='admin_log')
@staff_member_required
def set_certificates(request):
    students = User.objects.all() 
    certificates = Certificates.objects.all()
    if request.method == 'POST':
        try:
            username = request.POST.get('username') #Gets the value from the username field
            name_certificate = request.POST.get('name_certificate') #Gets the value from the name_certificate field
            vote = request.POST.get('vote') #Gets the value from the vote field
            student = User.objects.get(username=username) 
            certificate = Certificates.objects.get(name_certificate=name_certificate)
            new_certificate = SetCertificates(students=student, certificates=certificate,vote = vote) #Creates a new certificate object
            new_certificate.save() #Saves the new certificate object
            messages.success(request, 'Certificate assigned successfully.')
            return redirect ('certificates')
        except ValueError:
            messages.error(request, 'Please check your transactions or settings.')
        except Exception: 
            messages.error(request, 'An error occurred') 
    c_messages = messages.get_messages(request)
    return render(request, 'certificates/set_certificates.html', {'students': students, 'certificates' : certificates, 'c_messages' : c_messages})

def search_certificates(request):
    #Get all certificates
    certificates = SetCertificates.objects.all() 
    code = None
    if request.method == 'GET': 
        q_code = request.GET.get('code') #Gets the value from the code field
        if q_code:
            code = SetCertificates.objects.filter(certificates__code=q_code) #Filter certificates by code field
            if not code:  
                messages.error(request, 'Certificate not found') # This line sets an error message if the code is not found
    c_messages = messages.get_messages(request) # This line gets all the messages
    return render (request, 'certificates/search_certificates.html', {'code' : code, 'certificates' : certificates, 'c_messages': c_messages})

certificates/templates/certificates/addcertificates.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

<div class="spacer2"></div>

<form method="POST" class="form">
  <div class="grid grid--center">
    <div class="card">
      <div class="card-body">
        <h4>Add certificates</h4>
        {% csrf_token %}
        <div class="row">
          {% for field in form %}
            <div class="col">
              <div class="form-group">
              <label for="{{ field.id }}" class="cust">{{ field.label }}</label>
              {{ field }}
              </div>
            </div>
          {% endfor %}
        </div>
        <input type="submit" value="Add" class="button2">
      </div>
    </div>
  </div>
</form>

{% endblock %}

certificates/templates/certificates/search_certificates.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

<div class="spacer2"></div>

<form action="{% url 'search_certificates' %}" method="GET">
    <div class="grid grid--center">
        <div class="card">
            <div class="card-body">
                <h4>Enter the certificate code to view the transactions</h3>
                <div class="row">
                    <p><u><em>You can only search for a certificate after after assigning it.</em></u></p>
                    <input type="text" name="code">
                    <input type="submit" value="Search" class="button1">
                </div>
            </div>
        </div>
    </div>  
</form>

<div class="spacer"></div>
<div class="grid grid--center">
    {% if code %}
        <table>
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Certificate</th>
                    <th>Date</th>
                    <th>Vote</th>
                    <th>Tx</th>
                </tr>
            </thead>
            <tbody>
                {% for x in code %}
                <tr>
                    <td>{{ x.students.first_name }} {{ x.students.last_name }}</td>
                    <td>{{ x.certificates.name_certificate }}</td>
                    <td>{{ x.date }}</td>
                    <td>{{ x.vote }}</td>
                    <td><a href="https://goerli.etherscan.io/tx/{{ x.txid }}" target="_blank">{{ x.txid }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
</div>

{% endblock %}

certificates/templates/certificates/set_certificates.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

<div class="spacer2"></div>

<form method="POST" class="form1">
  <div class="grid grid--center">
    <div class="card">
      <div class="card-body">
        <h4><em>Select the student and the certificate to save it on the blockchain</em></h4>
        {% csrf_token %}
        <div class="row">
          <label for="id_students" class="label">Students:</label>
          <select class="form-input" id="username" name="username">
            {% for student in students %}
            <option value="{{ student.username }}">{{ student.username }}</option>
            {% endfor %}
          </select>
          <label for="id_certificates" class="label">Certificates:</label>
          <select class="form-input" id="name_certificate" name="name_certificate">
            {% for certificate in certificates %}
            <option value="{{ certificate.name_certificate }}">{{ certificate.name_certificate }}</option>
            {% endfor %}
          </select>
          <label for="id_vote" class="label">Vote:</label>
          <input type="number" class="form-input" id="id_vote" name="vote">
        </div>
        <input type="submit" value="Submit" class="button2">
      </div>
    </div>
  </div>
</form>

{% endblock %}